name: Go API Deployment to AWS ECR

on:
  push:
    branches: [ "main" ]

jobs:
  # STEP 1: TEST
  test-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Run Tests
        run: go test -v ./...

  # STEP 2: BUILD & PUSH TO AWS ECR
  build-and-push-to-ecr:
    needs: test-and-verify # Sadece testler geçerse çalışır
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-go-app # AWS'de oluşturduğun repo ismi
          IMAGE_TAG: latest
        run: |
          # Build the docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Push the image to AWS ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG